---
- name: wk backups
  hosts: westkingdom
  user: maint 
  become: true
  become_user: root 
  vars_files:
    - vars.yml

  roles:
    - { role: ../roles/backupdbs, tags: [ 'dbs' ] }
    - { role: ../roles/backupfiles, tags: [ 'files' ] }
    - { role: ../roles/notify, tags: [ 'notify' ] }
